version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./eng.traineddata:/app/eng.traineddata
      - ./.env:/app/.env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
