version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./model:/app/model
      - ./.env:/app/.env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
